# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Level Ground MMA
email: ali@levelgroundmma.org
description: >- # this means to ignore newlines until "baseurl:"
  At Level Ground, we value resilience, perseverance, community, and opportunity. 
  Our Mixed Martial Arts, Jiu Jitsu, Kickboxing, and Yoga offerings empower members of 
  all ages to embrace a healthy lifestyle while enjoying connection to a supportive, family-oriented community.
url: "http://levelgroundmma.org" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: levelgroundmma
github_username:  levelgroundmma

sass:
  style: compressed

# Build settings
permalink: /:categories/:title/
markdown: kramdown
theme:
plugins:
  - jekyll-feed

# Forestry Settings
collections:
  staff:
    output: true
    permalink: /:collection/:title/
  posts:
    output: true
    permalink: /news/:title/
  pages:
    output: true 
    permalink: /:title/

# Site Defaults
default_image: /assets/image/landing-hero.jpg
default_white_image: /assets/image/default_white.jpg
default_logo: /assets/image/lg_logo.png

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

