on: push
name: Build And Publish Website
jobs:
  Jekyll-Build-And-FTP-Deploy-Action:
    name: Jekyll-Build-And-FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 2
    - name: Build
      uses: jerryjvl/jekyll-build-action@v1
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@3.0.0
      with:
        ftp-server: ftp://ftp.levelgroundmma.org/
        ftp-username: github-webforestry@levelgroundmma.org
        ftp-password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./_site/
        git-ftp-args: --all
